services:
  database-host:
    container_name: database-host
    image: mysql:8.0
    depends_on:
      - backend-app
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - 3306
    networks:
      - net

  redis-host:
    container_name: redis-host
    image: redis:7.4
    depends_on:
      - backend-app
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --save 60 1 --loglevel warning --requirepass "$REDIS_PASSWORD"
    ports:
      - '6379:6379'
    expose:
      - 6379
    networks:
      - net

