"""Initial migration

Revision ID: 9fe10f3e896a
Revises: 
Create Date: 2023-10-01 13:38:25.464230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe10f3e896a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('web_identifier', sa.String(length=36), nullable=False),
    sa.Column('onboarding', sa.Enum('ONBOARDING_STEP_ONE', 'ONBOARDING_STEP_TWO', name='typeonboarding'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    op.create_table('users_historical_stock_price',
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('user_uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('symbol_stock', sa.String(length=20), nullable=False),
    sa.Column('open_price', sa.Float(precision=4, asdecimal=3), nullable=True),
    sa.Column('high_price', sa.Float(precision=4, asdecimal=3), nullable=True),
    sa.Column('low_price', sa.Float(precision=4, asdecimal=3), nullable=True),
    sa.Column('close_price', sa.Float(precision=4, asdecimal=3), nullable=True),
    sa.Column('date_stock', sa.Date(), nullable=False),
    sa.Column('time_stock', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('users_historical_stock_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_historical_stock_price_date_stock'), ['date_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_historical_stock_price_user_uuid'), ['user_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_historical_stock_price_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_historical_stock_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_historical_stock_price_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_historical_stock_price_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_historical_stock_price_date_stock'))

    op.drop_table('users_historical_stock_price')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))

    op.drop_table('users')
    # ### end Alembic commands ###
