"""add constraint in tables

Revision ID: f0a48f3e8cf8
Revises: 118611f9d4b6
Create Date: 2024-02-24 20:27:54.405562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0a48f3e8cf8'
down_revision = '118611f9d4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_symbol', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_symbol_symbol')
        batch_op.create_index(batch_op.f('ix_stock_symbol_symbol'), ['symbol'], unique=True)

    with op.batch_alter_table('user_stock_symbol', schema=None) as batch_op:
        batch_op.drop_index('ix_user_stock_symbol_uuid')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stock_symbol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.CHAR(length=36), nullable=False))
        batch_op.create_index('ix_user_stock_symbol_uuid', ['uuid'], unique=False)

    with op.batch_alter_table('stock_symbol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_symbol_symbol'))
        batch_op.create_index('ix_stock_symbol_symbol', ['symbol'], unique=False)

    # ### end Alembic commands ###
